version: "3.6"

services:
  app:
    build:
      context: .
      args:
        - KV_REST_API_READ_ONLY_TOKEN
        - KV_REST_API_TOKEN
        - KV_REST_API_URL
        - KV_URL
        - POSTGRES_DATABASE
        - POSTGRES_HOST
        - POSTGRES_PASSWORD
        - POSTGRES_PRISMA_URL
        - POSTGRES_URL
        - POSTGRES_URL_NO_SSL
        - POSTGRES_URL_NON_POOLING
        - POSTGRES_USER
        - PUPPETEER_SKIP_DOWNLOAD=true
        - S3_ACCESS_KEY
        - S3_BUCKET
        - S3_ENDPOINT
        - S3_REGION
        - S3_SECRET_KEY
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - .:/app
    environment:
      - KV_REST_API_READ_ONLY_TOKEN
      - KV_REST_API_TOKEN
      - KV_REST_API_URL
      - KV_URL
      - POSTGRES_DATABASE
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_PRISMA_URL
      - POSTGRES_URL
      - POSTGRES_URL_NO_SSL
      - POSTGRES_URL_NON_POOLING
      - POSTGRES_USER
      - PUPPETEER_SKIP_DOWNLOAD=true
      - S3_ACCESS_KEY
      - S3_BUCKET
      - S3_ENDPOINT
      - S3_REGION
      - S3_SECRET_KEY
